### ISSUE TITLE
CMake issues on Windows

### ISSUE THREAD

**Issue by mbechard** [AcademySoftwareFoundation/openexr#343] opened 2018-10-03 20:13 UTC
It seems like the correct way to build OpenEXR using CMake now is to use the CMake configuration that is in the root of the git tree. This is different than 2.2 and the instructions in IlmBase/OpenEXR sub directories in 2.3, which state you can use CMake from those subdirectories. When trying to do this  most of the generated projects are missing since the OPENEXR_BUILD_SHARED option (and many of the other options) aren't defined at that level of the CMake, and instead are only provided in the root CMake config file. If you set them manually things seem to work out, but you'd have to know to do that by looking at the config files themselves.

I think the instructions in the subdirectories should just be removed/amended for now until this is fixed. Also the separate downloads on the webpage makes this a little confusing too, since those aren't that useful on their own for CMake builds.

Thanks

**Comment by St0fF-NPL-ToM** [comment] 2019-06-19 14:47
Further issues, after figuring out how to get started:
when building shared OpenEXR (i.e. the dlls), the IlmImf.dll is not correctly installed.  Source seems to be the generated cmake_install.cmake script in "build/OpenEXR/IlmImf", which does not honour the install prefix correctly (regarding the dll).  Comparing f.e. "build/OpenEXR/IlmImfUtil/cmake_install.cmake" shows that those lines in the script differ completely.

**Comment by kdt3rd** [comment] 2019-07-17 13:17
A complete refactor of the cmake has taken place, modernizing cmake to match the "Modern CMake" guidelines and practices, we are formalizing the install documentation to include the top-level cmake as a super project instead of first suggesting the sub directories, so this should be fixed in the next release we make (if you want to test the master branch, and report any issues with the install under windows, that would be awesome, as I primarily develop on Linux). Thanks for the report!
(I will leave this open until we finish the documentation updates)

**Comment by kdt3rd** [comment] 2019-08-13 10:32
closing as we have confirmed functionality after the refactor of cmake. If there is still an issue with master, or forthcoming release, please let us know, and thanks for the original report.

**Closed as completed by kdt3rd** 2019-08-13 10:32 UTC
Labels: Documentation, Needs Discussion
