### ISSUE TITLE
cmake fails with -DPYTHON=ON

### ISSUE THREAD

**Issue by hjaekel** [AcademySoftwareFoundation/openexr#1094] opened 2021-07-16 21:43 UTC
When I try to generate the Python bindings for openexr 3.0.5 with `cmake` and `-DPYTHON=ON`, I get the following error:

```
-- The C compiler identification is GNU 10.3.1
-- The CXX compiler identification is GNU 10.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Imath was not found, installing from https://github.com/AcademySoftwareFoundation/Imath.git (v3.0.5)
-- Imath is configuring as a cmake sub project
-- Configure Imath 3.0.5, library API version: 28.0.2
-- Found Python: /usr/bin/python3.9 (found version "3.9.6") found components: Interpreter Development Development.Module Development.Embed 
-- Found Python3: /usr/bin/python3.9 (found version "3.9.6") found components: Interpreter Development Development.Module Development.Embed 
-- : Found Python 3.9.6
-- Found Python3 libraries: 39
--   -> Will install to: lib/python3.9/site-packages
-- Disabling boost-provided cmake config. If this causes problems, consider setting Boost_NO_BOOST_CMAKE variable to OFF
-- Found Boost: /usr/include (found version "1.76.0") found components: python39 missing components: python python3
--  -> Found Python 3 boost: Boost::python39
-- Found NumPy 1.21.0 for Python 3.9.6: /usr/lib/python3.9/site-packages/numpy/core/include
-- Performing Test OPENEXR_IMF_HAVE_SYSCONF_NPROCESSORS_ONLN
-- Performing Test OPENEXR_IMF_HAVE_SYSCONF_NPROCESSORS_ONLN - Success
-- Performing Test OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX
-- Performing Test OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX - Success
-- Looking for include file ucontext.h
-- Looking for include file ucontext.h - found
-- Performing Test IEX_HAVE_CONTROL_REGISTER_SUPPORT
-- Performing Test IEX_HAVE_CONTROL_REGISTER_SUPPORT - Failed
-- Looking for include file asm/sigcontext.h
-- Looking for include file asm/sigcontext.h - found
-- Performing Test IEX_HAVE_SIGCONTEXT_CONTROL_REGISTER_SUPPORT
-- Performing Test IEX_HAVE_SIGCONTEXT_CONTROL_REGISTER_SUPPORT - Success
-- Looking for include file semaphore.h
-- Looking for include file semaphore.h - found
-- Looking for sem_init in pthread
-- Looking for sem_init in pthread - found
-- Configure OpenEXR 3.0.5, library API version: 29.0.0
-- clang-format not found.
-- Configuring done
CMake Error: install(EXPORT "OpenEXR" ...) includes target "OpenEXR" which requires target "Imath" that is not in this export set, but in multiple other export sets: lib/cmake/Imath/ImathTargets.cmake, lib/cmake/Imath/ImathConfig.cmake.
An exported target cannot depend upon another target which is exported multiple times. Consider consolidating the exports of the "Imath" target to a single export.
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by meshula** [comment] 2021-07-17 03:49
Thanks for the report. Could you also tell us what command line you used to configure OpenEXR? - I realize you added -DPYTHON=ON, I'm wondering if there were any other configuration settings supplied.

**Comment by meshula** [comment] 2021-07-17 04:03
Also note another Python related build issue https://github.com/AcademySoftwareFoundation/openexr/issues/1066

**Comment by hjaekel** [comment] 2021-07-17 07:32
Here is the full command:
```
$ cmake --version
cmake version 3.21.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
$ cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_SHARED_LIBS=True \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_CXX_FLAGS="-Os -fomit-frame-pointer" \
    -DCMAKE_C_FLAGS="-Os -fomit-frame-pointer" \
    -DPYTHON=ON \
    -DDART_TESTING_TIMEOUT=3000
```

**Comment by meshula** [comment] 2021-07-22 02:11
I can reproduce this issue on several platforms. As a workaround, can you install Imath following the instructions here: https://github.com/AcademySoftwareFoundation/Imath/blob/master/INSTALL.md

You should then be able to build and install OpenEXR, but omit the -DPYTHON=ON flag.

Note that there are no OpenEXR python bindings provided in this repository, so you won't be missing out on anything.

The overall issue seems to be that the cmake scripts become confused by the Python binding module for Imath exporting Imath, which it probably shouldn't at all, since there's no downstream dependency on cmake generating that export.

**Comment by kdt3rd** [comment] 2021-09-05 03:41
I have submitted a pull request against the imath repository to fix this.

**Comment by kdt3rd** [comment] 2021-09-19 05:06
This is addressed in the upstream imath library.

**Closed as completed by kdt3rd** 2021-09-19 05:06 UTC
Labels: Build, Bug
