### ISSUE TITLE
Possible compile/install issues in PyIlmBase with multiple jobs

### ISSUE THREAD

**Issue by waebbl** [AcademySoftwareFoundation/openexr#348] opened 2018-10-11 19:19 UTC
When building PyIlmBase with more than one jobs, i.e. `make -jN` for N>1 it can fail in linking imathmodule, due to PyImath isn't linked yet. The `Makefile.am` currently using `-lPyImath` instead of `libPyImath.la` in its `imathmodule_la_LIBADD` line in contrast how the other modules do it.
The patch at https://github.com/gentoo/gentoo/blob/master/dev-python/pyilmbase/files/pyilmbase-2.3.0-link-pyimath.patch should solve this issue and works on gentoo.
Also, the install target can fail if called with more than one job.

**Comment by kdt3rd** [comment] 2019-08-13 10:45
Closing as duplicate of #336

**Closed as completed by kdt3rd** 2019-08-13 10:45 UTC
Labels: Build
