### ISSUE TITLE
PyIlmBase 2.2/2.3 fails to install successfully if set to use more than one core

### ISSUE THREAD

**Issue by dracwyrm** [AcademySoftwareFoundation/openexr#336] opened 2018-09-01 09:48 UTC
Hi,

Note: This is for the Autotools build system, not CMake.
During the make install phase, if the -j option is greater than 1, the source fails to install giving this error:
```
make -j2 DESTDIR=/var/tmp/portage/dev-python/pyilmbase-2.3.0/image/ install 
Making install in config
make[1]: Entering directory '/var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/config'
make[2]: Entering directory '/var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/config'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/include/OpenEXR'
 /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c -m 644 PyIlmBaseConfig.h '/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/include/OpenEXR'
make[2]: Leaving directory '/var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/config'
make[1]: Leaving directory '/var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/config'
Making install in PyIex
make[1]: Entering directory '/var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/PyIex'
make[2]: Entering directory '/var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/PyIex'
 /bin/mkdir -p '/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64'
 /bin/mkdir -p '/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64/python2.7/site-packages'
 /bin/sh ../libtool   --mode=install /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c   libPyIex.la '/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64'
 /bin/sh ../libtool   --mode=install /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c   iexmodule.la '/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64/python2.7/site-packages'
libtool: install: /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c .libs/libPyIex.so.24.0.2 /var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64/libPyIex.so.24.0.2
libtool: install: warning: relinking `iexmodule.la'
libtool: install: (cd /var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/PyIex; /bin/sh /var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/libtool  --tag CXX --mode=relink x86_64-pc-linux-gnu-g++ -pipe -march=native -O2 -w -pipe -std=c++14 -I/usr/include/boost -I/usr/include/python2.7 -avoid-version -module -Wl,-O1 -Wl,--as-needed -L/usr/lib64 -L/usr/lib64 -o iexmodule.la -rpath /usr/lib64/python2.7/site-packages iexmodule.lo libPyIex.la -lboost_python-2.7 -lpython2.7 -inst-prefix-dir /var/tmp/portage/dev-python/pyilmbase-2.3.0/image/)
libtool: install: (cd /var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64 && { ln -s -f libPyIex.so.24.0.2 libPyIex.so.24 || { rm -f libPyIex.so.24 && ln -s libPyIex.so.24.0.2 libPyIex.so.24; }; })
libtool: install: (cd /var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64 && { ln -s -f libPyIex.so.24.0.2 libPyIex.so || { rm -f libPyIex.so && ln -s libPyIex.so.24.0.2 libPyIex.so; }; })
libtool: install: /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c .libs/libPyIex.lai /var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64/libPyIex.la
libtool: install: warning: remember to run `libtool --finish /usr/lib64'
 /bin/mkdir -p '/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/include/OpenEXR'
 /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c -m 644 PyIex.h PyIexExport.h PyIexTypeTranslator.h '/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/include/OpenEXR'
libtool: relink: x86_64-pc-linux-gnu-g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../lib64/crti.o /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/crtbeginS.o  .libs/iexmodule.o   -L/usr/lib64 -L/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64 -lPyIex -lz -lImath -lHalf -lIexMath -lIlmThread -lIex -lboost_python-2.7 -lpython2.7 -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0 -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/crtendS.o /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../lib64/crtn.o  -march=native -O2 -Wl,-O1 -Wl,--as-needed   -pthread -Wl,-soname -Wl,iexmodule.so -o .libs/iexmodule.so
libtool: install: /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c .libs/iexmodule.soT /var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64/python2.7/site-packages/iexmodule.so
libtool: install: /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c .libs/iexmodule.lai /var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64/python2.7/site-packages/iexmodule.la
libtool: install: warning: remember to run `libtool --finish /usr/lib64/python2.7/site-packages'
make[2]: Leaving directory '/var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/PyIex'
make[1]: Leaving directory '/var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/PyIex'
Making install in PyImath
make[1]: Entering directory '/var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/PyImath'
make[2]: Entering directory '/var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/PyImath'
 /bin/mkdir -p '/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64'
 /bin/mkdir -p '/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64/python2.7/site-packages'
 /bin/sh ../libtool   --mode=install /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c   libPyImath.la '/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64'
 /bin/sh ../libtool   --mode=install /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c   imathmodule.la '/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64/python2.7/site-packages'
libtool: install: warning: relinking `imathmodule.la'
libtool: install: (cd /var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/PyImath; /bin/sh /var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/libtool  --tag CXX --mode=relink x86_64-pc-linux-gnu-g++ -pipe -march=native -O2 -w -pipe -std=c++14 -I/usr/include/boost -I/usr/include/python2.7 -avoid-version -module -Wl,-O1 -Wl,--as-needed -L/usr/lib64 -L/usr/lib64 -o imathmodule.la -rpath /usr/lib64/python2.7/site-packages imathmodule.lo PyImathFun.lo PyImathBasicTypes.lo -lPyImath -lboost_python-2.7 -lpython2.7 -inst-prefix-dir /var/tmp/portage/dev-python/pyilmbase-2.3.0/image/)
libtool: install: warning: relinking `libPyImath.la'
libtool: install: (cd /var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/PyImath; /bin/sh /var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/libtool  --tag CXX --mode=relink x86_64-pc-linux-gnu-g++ -pipe -march=native -O2 -w -pipe -std=c++14 -I/usr/include/boost -I/usr/include/python2.7 -version-info 24:2:0 -no-undefined -Wl,-O1 -Wl,--as-needed -L/usr/lib64 -L/usr/lib64 -o libPyImath.la -rpath /usr/lib64 PyImath.lo PyImathAutovectorize.lo PyImathBox2Array.lo PyImathBox3Array.lo PyImathBox.lo PyImathColor3.lo PyImathColor4.lo PyImathEuler.lo PyImathFixedArray.lo PyImathFrustum.lo PyImathLine.lo PyImathMatrix33.lo PyImathMatrix44.lo PyImathPlane.lo PyImathQuat.lo PyImathRandom.lo PyImathShear.lo PyImathStringArray.lo PyImathStringTable.lo PyImathTask.lo PyImathUtil.lo PyImathFixedVArray.lo PyImathVec2fd.lo PyImathVec2si.lo PyImathVec3fd.lo PyImathVec3siArray.lo PyImathVec3si.lo PyImathVec4fd.lo PyImathVec4siArray.lo PyImathVec4si.lo -lz ../PyIex/libPyIex.la -lImath -lHalf -lIex -lIexMath -lIlmThread -pthread -lboost_python-2.7 -lpython2.7 -inst-prefix-dir /var/tmp/portage/dev-python/pyilmbase-2.3.0/image/)
libtool: relink: x86_64-pc-linux-gnu-g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../lib64/crti.o /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/crtbeginS.o  .libs/imathmodule.o .libs/PyImathFun.o .libs/PyImathBasicTypes.o   -L/var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/PyIex/.libs -L/usr/lib64 -L/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64 -lPyImath -lPyIex -lz -lImath -lHalf -lIexMath -lIlmThread -lIex -lboost_python-2.7 -lpython2.7 -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0 -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/crtendS.o /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../lib64/crtn.o  -march=native -O2 -Wl,-O1 -Wl,--as-needed   -pthread -Wl,-soname -Wl,imathmodule.so -o .libs/imathmodule.so
libtool: relink: x86_64-pc-linux-gnu-g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../lib64/crti.o /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/crtbeginS.o  .libs/PyImath.o .libs/PyImathAutovectorize.o .libs/PyImathBox2Array.o .libs/PyImathBox3Array.o .libs/PyImathBox.o .libs/PyImathColor3.o .libs/PyImathColor4.o .libs/PyImathEuler.o .libs/PyImathFixedArray.o .libs/PyImathFrustum.o .libs/PyImathLine.o .libs/PyImathMatrix33.o .libs/PyImathMatrix44.o .libs/PyImathPlane.o .libs/PyImathQuat.o .libs/PyImathRandom.o .libs/PyImathShear.o .libs/PyImathStringArray.o .libs/PyImathStringTable.o .libs/PyImathTask.o .libs/PyImathUtil.o .libs/PyImathFixedVArray.o .libs/PyImathVec2fd.o .libs/PyImathVec2si.o .libs/PyImathVec3fd.o .libs/PyImathVec3siArray.o .libs/PyImathVec3si.o .libs/PyImathVec4fd.o .libs/PyImathVec4siArray.o .libs/PyImathVec4si.o   -L/usr/lib64 -L/var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64 -lPyIex -lz -lImath -lHalf -lIexMath -lIlmThread -lIex -lboost_python-2.7 -lpython2.7 -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0 -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/crtendS.o /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../lib64/crtn.o  -march=native -O2 -Wl,-O1 -Wl,--as-needed -pthread   -pthread -Wl,-soname -Wl,libPyImath.so.24 -o .libs/libPyImath.so.24.0.2
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lPyImath
collect2: error: ld returned 1 exit status
libtool: install: error: relink `imathmodule.la' with the above command before installing it
make[2]: *** [Makefile:523: install-pyexecLTLIBRARIES] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: install: /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c .libs/libPyImath.so.24.0.2T /var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64/libPyImath.so.24.0.2
libtool: install: (cd /var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64 && { ln -s -f libPyImath.so.24.0.2 libPyImath.so.24 || { rm -f libPyImath.so.24 && ln -s libPyImath.so.24.0.2 libPyImath.so.24; }; })
libtool: install: (cd /var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64 && { ln -s -f libPyImath.so.24.0.2 libPyImath.so || { rm -f libPyImath.so && ln -s libPyImath.so.24.0.2 libPyImath.so; }; })
libtool: install: /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c .libs/libPyImath.lai /var/tmp/portage/dev-python/pyilmbase-2.3.0/image//usr/lib64/libPyImath.la
libtool: install: warning: remember to run `libtool --finish /usr/lib64'
make[2]: Leaving directory '/var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/PyImath'
make[1]: *** [Makefile:745: install-am] Error 2
make[1]: Leaving directory '/var/tmp/portage/dev-python/pyilmbase-2.3.0/work/pyilmbase-2.3.0-abi_x86_64.amd64/PyImath'
make: *** [Makefile:489: install-recursive] Error 1
```
I can provide the whole build log if needed.

Cheers,
Jon

**Comment by kdt3rd** [comment] 2018-09-07 22:18
strange, I compile with -j8 most of the time (on a 4 core machine) and have not noticed this. However, I guess I compile first and then install (make -j8 && make install). Does that method work for you? If so, it will help narrow down where the dependency is missing.

**Comment by dracwyrm** [comment] 2018-09-09 09:31
This is the process that the ebuild uses as it will make then do make install. On Gentoo, there is a makeopts variable that will be used for both build and install unless overridden. This is the ebuild: https://github.com/dracwyrm/gentoo-ebuilds/blob/master/dev-python/pyilmbase/pyilmbase-2.3.0.ebuild
I couldn't get it to build against Python 3.5 at all, so it's set to 2.7. The multilib lines means that it will install both the 32 and 64 bit versions.

To clarify, it does build with make -j4, but only installs on make install -j1.

**Comment by meshula** [comment] 2018-09-09 18:49
What issue did you run into versus Python 3.5? I've built using the root cmake file, on Windows, against Python 3.5, so it's possible in at least one case.

**Comment by dracwyrm** [comment] 2018-09-10 09:20
@meshula It doesn't even configure for me.
```
checking for python version... 3.5
checking for python platform... linux
checking for python script directory... ${prefix}/lib64/python3.5/site-packages
checking for python extension module directory... ${exec_prefix}/lib64/python3.5/site-packages
checking for boost::python... no
*** Could not run the boost::python test program, checking why...
*** The boost::python test program could be compiled, but could not be dynamically.
*** or statically linked.
***
*** Make sure the LDFLAGS points to the location of the boost::python library.
*** (e.g. -L/usr/local/lib).
*** If the run-time linker is not finding boost::python, you'll need to set your
*** LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf to point
*** to the installed location  Also, make sure you have run ldconfig if that
*** is required on your system.
***
*** Flags used by the test:
***     cflags: -march=native -O2 -w -pipe -std=c++14 -I/usr/include/boost -I/usr/include/python3.5m -march=native -O2 -w -pipe -std=c++14 -I/usr/include/boost -I/usr/include/python3.5m 
***     ldflags: -Wl,-O1 -Wl,--as-needed  -L/usr/lib64 -L/usr/lib64 -Wl,-O1 -Wl,--as-needed  -L/usr/lib64 -L/usr/lib64
***
*** You can also run configure with --disable-boostpythontest to skip this test.
configure: error: Could not compile boost::python test program.
```
Also, `--disable-boostpythontest` does not work and there is nothing in the configure scripts to make this skip the test. This is using Autotools, not CMake.

**Comment by cary-ilm** [comment] 2019-06-26 03:59
Looking into the OpenEXR backlog...

Is the -j problem possibly the same as #348?

**Comment by meshula** [comment] 2019-06-27 00:35
It's possible as the issue is a linking problem. I wonder if @dracwyrm could test if the patch proposed in #348 solves the problem?

**Comment by cary-ilm** [comment] 2019-09-05 17:12
Closing the issue for now, feel free to re-open or file a new issue if you need further help.

**Closed as completed by cary-ilm** 2019-09-05 17:12 UTC
