### ISSUE TITLE
DWA compression causes artifacts in black areas bordering colored edges

### ISSUE THREAD

**Issue by efleurant** [AcademySoftwareFoundation/openexr#552] opened 2019-09-05 21:46 UTC
Hi,

We seem to be getting artifacts or odd values in black areas bordering non-zero "colored" edges.
In other words, for a black pixel (0,0,0) bordering another non-zero pixel in an uncompressed file, the value of that black pixel changes to an unusual value. (_for example (0,0,0) to (1.4e-6,12.0,0.117) when picking the value in Nuke_). Obviously, as we drop the compression level, the less artifacts we get. If we set the compression level to 0, we get no odd values.

It's very similar to what we would be getting in a low compressed jpeg file. Is it a behavior that's inherent to all DCT-based image compression algorithm?

I have included a couple of exr to reproduce the issue. The attached zip files contain an example with two AOVs (beautyKey and Albedo) both in uncompressed and DWAB exrs.
An two other exr with the result of dividing (in Nuke) the two AOVs in uncompressed and DWAB. The DWAB were exported from the uncompressed file with the default compression level (45).

Finally, if this is the expected result, is DWAB a recommended compression choice for rendering AOVs?

[test_dwab_artifacts.zip](https://github.com/openexr/openexr/files/3581282/test_dwab_artifacts.zip)

**Comment by peterhillman** [comment] 2019-09-05 23:40
I think this is expected behaviour: the compressed image looks visually similar to the original, but is mathematically different. I would expect to see effects like that in all lossy compressed images. Dividing one lossy compressed image by another is sure to exaggerate any differences introduced by compression.

I would avoid using lossy compression algorithms like DWAB for AOVS and any other intermediate images, and only use that for final output.

It would be worth testing all compression options for read/write speed, file size, and quality of final result. It seems ZIP compression is about 2x the size of DWAB at level 45, but still 5x smaller than uncompressed, so may be a better choice for these images.

**Comment by karlrasche** [comment] 2019-09-05 23:51
Yeah, thats one of the annoying side effects. You can also get the black
side of an edge to flip to small negative values, which shows up as odd
halos in you comp.

Sometimes you can kill them by looking at alpha and forcing things to zero
when a==0. That can have side effects if you have valid data with a==0 in
your frame, so beware.

The right fix is to encode some extra data to force zeros to decode as
zero. Thought about it a bit, but never implemented it.

**Comment by efleurant** [comment] 2019-09-09 21:07
Thanks for the feedback all!

@karlrasche : Yeah I thought about that approach too, but I'm wondering if that's something that could be implemented on the encoder side (as an option or as another variation of the DWA compression).

I don't know if the following could work; The encoder could:
- Map the black pixels of the source image first.
- Encode the image like it normally does.
- Zero out the pixel defined in the mapping from the first step.

Would that make any sense?

**Comment by karlrasche** [comment] 2019-09-09 23:43
I thnk its challenging to do without signallong o the decoder. The problem
is that you want to constrain values in the spatial domain, but quantize in
the dct domain. So the question of “what to zero” gets challenging.

Karl

**Comment by efleurant** [comment] 2019-09-10 14:12
If implemented on the decoder side, how would we keep backward compatibility if a given user doesn't want to use this new "feature". Or would it require to create a new flavor of DWA?

Also, is it possible to promote this post as a feature request, don't really know how to do that here.
I'm assuming this could make DWA compression usable for intermediate images... or a least to a certain extent.

Thanks a lot for the feeback btw.

**Comment by peterhillman** [comment] 2019-09-10 20:38
My guess is that the "zero map" would require a new variant of DWA, which wouldn't be compatible with DWAA and DWAB, but there are other issues that could also be addressed cleanly in a new variant.

You could simulate the zero map by using an uncompressed image to detect zeroes and correct the DWA image after decompression. That would help to work out the fine details of how detection works and make sure it doesn't introduce artifacts of its own. The zeroes-not-staying-zeroes issue may not be the only problem that appear using lossy compression for intermediate images, and it may be possible to mitigate those too.

Another approach might be to use variable compression for each block, so store blocks with zeroes in them with higher quality, so reducing the artifacts to some extent. That might be achievable in way that's compatible with the existing DWA variants. It would result in larger files, but the zero map will also take extra space.

**Comment by karlrasche** [comment] 2019-09-11 00:10
Reaching way back, so I may be wrong on some details, but..

I think there’s a few extra bytes in the “header” of the compressed payload
that I stuck in for future extensability. There’s also a explicit version
number in there, that decoders will fail to read if the file version is
newer than the decoder.  So if you add a feature and want older code to
fail, you can rev this version without having to make a whole new
compression enum.

For something like a zero map, if you wrote the compressed data at the end
of the block, legacy decoders should skip it, so backwards compatability
may be possible.

The logic for picking zeros may be complicated.. do you look at rgb and
alpha? What about yuv? If the image is rb, what do you do?

You probably want the smallest codeword to signal either a full zero or
nonzero 8x8 block. Beyond that, I never looked at what the ideal mask
patterns might be. A byte per row is easy, though it seems too easy to be
optimal...

Karl

**Comment by cary-ilm** [comment] 2019-10-18 01:00
Have we concluded that this is a feature, not a bug? Is there anything more to do or report here? Can we close the issue for now?

**Comment by efleurant** [comment] 2019-10-18 01:43
It's indeed not a bug, so I guess we can close the issue just as long as it stays in the feature request bin :)

Thanks! Cheers!

**Comment by cary-ilm** [comment] 2019-11-21 21:25
Closing the issue for now, feel free to re-open or file a new issue if you need further help.

**Closed as completed by cary-ilm** 2019-11-21 21:25 UTC
Labels: Feature Request, Needs Discussion
