### ISSUE TITLE
Open EXR: Missing PyIlmBase Libraries and Files

### ISSUE THREAD

**Issue by Zyssna** [AcademySoftwareFoundation/openexr#744] opened 2020-05-26 19:38 UTC
Hi everyone,

I'm a VFX and Computer Arts student who is building OpenVDB against Maya installed on my Windows desktop. I am new to coding and the GitHub community.

Any help would be appreciated.

Following the tutorials and guidelines:

https://github.com/ramakarl/win_openvdb
https://www.openvdb.org/documentation/doxygen/dependencies.html

I successfully downloaded and built,

ILMBase
ZLib

but when I attempted both the recommended version 2.2.0 and the latest 2.5.1, the generation in CMake or the release in VS2019 failed because of missing files.

Configure ILMBASE Version: 2.5.1 Lib API: 25.0.0
-- WARNING pkg-config generation disabled
Configure OpenEXR Version: 2.5.1 Lib API: 25.0.0
CMake Error at PyIlmBase/CMakeLists.txt:14 (include):
  include could not find load file:

    config/ParseConfigure.cmake

CMake Warning at PyIlmBase/CMakeLists.txt:16 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.

CMake Error at PyIlmBase/CMakeLists.txt:27 (include):
  include could not find load file:

    config/PyIlmBaseSetup.cmake

Could NOT find Python2 (missing: Python2_EXECUTABLE Python2_LIBRARIES Python2_INCLUDE_DIRS Interpreter Development) 
CMake Warning at PyIlmBase/CMakeLists.txt:54 (message):
  : Unable to find Python2 interpreter or development libraries

: Found Python 3.7.5
Found Python3 libraries: 37
  -> Will install to: Lib/site-packages
Disabling boost-provided cmake config. If this causes problems, consider setting Boost_NO_BOOST_CMAKE variable to OFF
Could NOT find Boost (missing: Boost_INCLUDE_DIR) 
CMake Warning at PyIlmBase/CMakeLists.txt:184 (message):
  Unable to find boost::python library, disabling PyIlmBase.  If you believe
  this is wrong, check the cmake documentation and see if you need to set
  Boost_ROOT or Boost_NO_BOOST_CMAKE

CMake Error at CMakeLists.txt:86 (include):
  include could not find load file:

    cmake/clang-format.cmake

**Comment by meshula** [comment] 2020-05-29 20:53
In order to accomplish what you want to do it's not just a matter of installing boost and building OpenEXR.There is a lot more information on this page - https://www.openvdb.org/documentation/doxygen/build.html#buildGuide in the Maya section - but it assumes a lot about what you already know how to do.  I suggest reaching out in the OpenVdb issues page for guidance.

**Comment by cary-ilm** [comment] 2020-07-16 00:59
Is this still an issue? I'm not clear from your description if the problem is triggered from building OpenVDB or if you're trying to build and install OpenEXR directly.

**Comment by cary-ilm** [comment] 2020-07-30 18:05
Closing for now, but feel free to reopen or file a new issue.

**Closed as completed by cary-ilm** 2020-07-30 18:05 UTC
Labels: Awaiting Feedback
